/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MapJNI */

#ifndef _Included_MapJNI
#define _Included_MapJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef MapJNI_LOOK_RADIUS
#define MapJNI_LOOK_RADIUS 5L
/*
 * Class:     MapJNI
 * Method:    getGoldToWin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MapJNI_getGoldToWin
  (JNIEnv *, jobject);

/*
 * Class:     MapJNI
 * Method:    getMapName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MapJNI_getMapName
  (JNIEnv *, jobject);

/*
 * Class:     MapJNI
 * Method:    getMapWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MapJNI_getMapWidth
  (JNIEnv *, jobject);

/*
 * Class:     MapJNI
 * Method:    getMapHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MapJNI_getMapHeight
  (JNIEnv *, jobject);

/*
 * Class:     MapJNI
 * Method:    getTile
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_MapJNI_getTile
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     MapJNI
 * Method:    replaceTile
 * Signature: (IIC)V
 */
JNIEXPORT void JNICALL Java_MapJNI_replaceTile
  (JNIEnv *, jobject, jint, jint, jchar);

/*
 * Class:     MapJNI
 * Method:    setWin
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_MapJNI_setWin
  (JNIEnv *, jobject, jstring);

/*
 * Class:     MapJNI
 * Method:    setName
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_MapJNI_setName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
